#! /usr/bin/perl
use Sympatic;
use Net::Netrc;

my $muttrc_fmt='
set smtp_url=smtps://%s
set smtp_pass=%s
';

my %doable_for =
( -muttrc => sub {
        my $credentials = Net::Netrc->lookup(@_)
            or die join " ", "can't get credentials for ", @_;
        printf $muttrc_fmt
        , ( join '@', reverse  @_ )
        , $c->password;

    }
);

my $action = $doable_for{$ARGV[0]} or do {
    say $_//'' for Net::Netrc->lookup(@ARGV)->lpa;
    exit;
};

shift @ARGV;
$action->(@ARGV);
